server:
  port: 8081
spring:
  application:
    name: client-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:clients;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate: { ddl-auto: update }
    open-in-view: false
  rabbitmq:
    host: "${SPRING_RABBITMQ_HOST:localhost}"
    listener:
      simple:
        auto-startup: "${RABBIT_LISTENER_AUTO_STARTUP:false}"
  jackson: { default-property-inclusion: non_null }
management:
  endpoints:
    web:
      exposure: { include: health,info }
bank:
  messaging:
    enabled: false
